FROM frolvlad/alpine-oraclejdk8:slim
VOLUME /tmp
ADD roadpricing-0.0.1-SNAPSHOT.jar roadpricing.jar
RUN sh -c 'touch /roadpricing.jar'
ENV JAVA_OPTS=""
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /roadpricing.jar" ]
