FROM frolvlad/alpine-oraclejdk8:slim
VOLUME /tmp
ADD RoadPricing-0.0.1-SNAPSHOT.jar RoadPricing.jar
RUN sh -c 'touch /RoadPricing.jar'
ENV JAVA_OPTS=""
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /RoadPricing.jar" ]
