FROM frolvlad/alpine-oraclejdk8:slim
VOLUME /tmp
ADD roadPricing-0.0.1-SNAPSHOT.jar roadPricing.jar
RUN sh -c 'touch /roadPricing.jar'
ENV JAVA_OPTS=""
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /roadPricing.jar" ]
